load_pdf:
  description: >
    Cargar y procesar PDF del C칩digo de Tr치nsito
  expected_output: >
    PDF procesado y disponible para RAG
  agent: ingestor

answer_question:
  description: >
    Responder preguntas sobre el C칩digo
  expected_output: >
    Respuesta clara y formal basada en el C칩digo
  agent: responder
